### ISSUE TITLE
[Feature request] Add support for Makefile's

### ISSUE THREAD

**Issue by lixvbnet** [stevearc/aerial.nvim#108]
Is it possible to add support for Makefile's? (e.g. list all make targets).  It would make it easier to navigate a large Makefile. (There seems to be no LSP for Makefile)

**Comment by stevearc** [comment]
Done! Support added for treesitter backend. It's pretty basic, just enumerating all the rules. LMK if you think there's anything else that could be added.

**Comment by lixvbnet** [comment]
@stevearc this works great for me! Thank you for making this happen! 👍

**Comment by lixvbnet** [comment]
@stevearc Btw, how do I customize the icon, or could you change the default one? (for Makefile only, other icons look beautiful).  I'd like to set it to be like that in IDEA, which looks prettier,

![image](https://user-images.githubusercontent.com/75612664/170644359-5b8aa847-3517-4785-a274-0014a85eb726.png)

**Comment by stevearc** [comment]
At the moment the symbol *types* are tied to the LSP spec, so I used 'Interface' (customized by `icons = { Interface = '' }` option in setup). I think that, now that aerial supports Makefiles, markdown, and rst, perhaps it's time to extend the symbol spec. I'll investigate that this weekend

**Comment by stevearc** [comment]
Okay I wrote up an implementation that added a `Title` symbol, tested it, committed it, and then scrapped it because I didn't like the approach 😅

What I ended up doing instead was making the `icons` option take a filetype map. This means that you can specify the icons directly (this was how it worked before):
```lua
require('aerial').setup({
  icons = {
    Interface = 'I',
    Function = 'F',
  }
})
```
OR you can specify them on a per-filetype basis
```lua
require('aerial').setup({
  icons = {
    markdown = {
      Interface = 'I',
    },
    make = {
      Interface = 'T',
    },
    ['_'] = {
      -- The underscore key is for any unmatched filetypes
    },
  }
})
```
This should allow you to customize the icons for any filetype as much as you want.
