### ISSUE TITLE
[help] No LSP clients support textDocument/documentSymbol

### ISSUE THREAD

**Issue by alexzanderr** [stevearc/aerial.nvim#12]
hey, very nice plugin.
i have neovim 0.6 and this plugin (https://github.com/neovim/nvim-lspconfig) installed.

i pasted 
```lua
lua << EOF
local aerial = require'aerial'

local custom_attach = function(client)
  aerial.on_attach(client)

  -- Aerial does not set any mappings by default, so you'll want to set some up
  -- Toggle the aerial window with <leader>a
  vim.api.nvim_buf_set_keymap(0, 'n', '<leader>a', '<cmd>AerialToggle!<CR>', {})
  -- Jump forwards/backwards with '{' and '}'
  vim.api.nvim_buf_set_keymap(0, 'n', '{', '<cmd>AerialPrev<CR>', {})
  vim.api.nvim_buf_set_keymap(0, 'n', '}', '<cmd>AerialNext<CR>', {})
  -- Jump up the tree with '[[' or ']]'
  vim.api.nvim_buf_set_keymap(0, 'n', '[[', '<cmd>AerialPrevUp<CR>', {})
  vim.api.nvim_buf_set_keymap(0, 'n', ']]', '<cmd>AerialNextUp<CR>', {})

  -- This is a great place to set up all your other LSP mappings
end

-- Set up your LSP clients here, using the custom on_attach method
require'lspconfig'.vimls.setup{
  on_attach = custom_attach,
}
EOF
```
in my init.vim

when im trying to run `AerialToggle!` i get `No LSP clients support textDocument/documentSymbol`.

what am i missing?

im new to neovim and lua configurations. can someone please guide me to run this plugin successfully?

**Comment by stevearc** [comment]
First, welcome to neovim!

To get aerial working you'll need to first get a functioning LSP configuration. This isn't too difficult, and I'll provide some guidance below, but you may also want to consider looking into a preconfigured project like [LunarVim](https://www.lunarvim.org/). If you want a lot of IDE features and don't want to have to go searching for all the plugins and configuring them yourself, LunarVim will get you up and running faster and with less hassle. If you want to tightly control your vim config, you're more of a minimalist, or if you want to learn more about the internals, then setting things up yourself is probably the way to go.

### Step 1 - debugging
[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) provides a command `:LspInfo` that will help you check the status of your LSP servers. Here's some example output:
```
Configured servers: sumneko_lua, pyright, sorbet, gdscript, efm, bashls, clangd, gopls, flow, cssls, omnisharp, vimls, html, yamlls, rust_analyzer, tsserver, jsonls
Neovim logs at: /home/stevearc/.cache/nvim/lsp.log

2 client(s) attached to this buffer: pyright, efm

  Client: pyright (id: 1 pid: 8919)
  	root:      /home/stevearc/ws/pypicloud
  	filetypes: python
  	cmd:       pyright-langserver --stdio

  Client: efm (id: 2 pid: 8920)
  	root:      /home/stevearc/ws/pypicloud
  	filetypes: javascriptreact, css, vim, yaml, jsonc, php, typescript.jsx, typescript, javascript.jsx, typescriptreact, lua, md, python, supercollider, html, javascript, xml, sh, rst
  	cmd:       efm-langserver -logfile /tmp/efm.log -loglevel 4
```

My suspicion is that your command will tell you that you only have a single configured server (`vimls`), and that you have 0 clients attached to the buffer. That's because you haven't configured or installed other language servers!

### Step 2 - configure the servers
There is a section on [enabling additional language servers](https://github.com/neovim/nvim-lspconfig#enabling-additional-language-servers) in the main nvim-lspconfig README. That links to a doc that has [a full list of all available language servers](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md). Find the language server you want to use and add the setup snippet to your config. For example, if I'm using Python and I want to use the Pyright language server, I can see that I should do
```lua
require'lspconfig'.pyright.setup{}
```
In *most* cases, you won't have to supply any of the other arguments (e.g. `cmd`, `filetypes`, `settings`, etc), so don't bother reading up on them unless the default config doesn't work. Note that the integration with aerial requires the `on_attach` hook, so you'll need to update the line to pass that:
```lua
require'lspconfig'.pyright.setup{
  on_attach = custom_attach,
}
```

Now if you run `:LspInfo`, you should see your language server appear in the "configured servers" list, but you probably still don't see anything in the "attached clients" section (if you do, great! You're done). For that, we'll need to go to the final step

### Step 3 - install the servers
You need to install the language server so nvim-lspconfig can run it. You can install it by hand if you want; all you need is the executable that the config is looking for. You can see what command it needs by again going to the [list of all language servers](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md) and looking at the `cmd` under "Default values". For example, the Pyright language server is going to look for the `pyright-langserver` executable. From there I could google Pyright, find its [github page](https://github.com/microsoft/pyright), and work out how to install it manually (in this case, `npm install -g pyright`). In practice, many language servers are on NPM and are installed via `npm install -g`. 

The *easy* way to install a language server is by using one of the plugins [listed here](https://github.com/neovim/nvim-lspconfig/wiki/Installing-language-servers-automatically). They will provide a simple `:LspInstall` command that should Just Work.

Hopefully this gets you unstuck!

Lastly, if you do decide to use LunarVim, this is the config necessary to use aerial (put in ~/.config/lvim/config.lua):
```lua
lvim.lsp.on_attach_callback = function(client, bufnr)
  require('aerial').on_attach(client, {})
end
lvim.plugins = {
  {'stevearc/aerial.nvim'}
}
```

**Comment by alexzanderr** [comment]
> My suspicion is that your command will tell you that you only have a single configured server (vimls)

that is correct.
![image](https://user-images.githubusercontent.com/54772464/133247991-1995efcf-abf5-40f7-9890-73a1bbc088c8.png)

okey, i added the line with `require pyright` and installed pyright using `npm` globally and now when i do `:LSPInfo`
![image](https://user-images.githubusercontent.com/54772464/133248695-84eca266-2751-4c09-a549-a381ec36f9ea.png)

i see that i get the beautiful floating errors and warning that i really wanted for a long time. 
![image](https://user-images.githubusercontent.com/54772464/133249260-d33aa597-9960-475a-ae64-733b00343201.png)
so i guess the language server its working.


now when i run `AerialToggle`:
![image](https://user-images.githubusercontent.com/54772464/133249598-0b33d296-c50e-424f-b50b-4b927aa40c0e.png)
omg, its working.

thank you so much, man, for this beautiful and easy tutorial!!

you just helped enter through the portal of nvim with lua and LSP features.

now makes sense!
