### ISSUE TITLE
Lsp callback error from name is nil.

### ISSUE THREAD

**Issue by Azrealy** [stevearc/aerial.nvim#126]
https://github.com/stevearc/aerial.nvim/blob/67bddeca28c476731ed5da64876b7f71d01190d1/lua/aerial/backends/lsp/callbacks.lua#L29
My nvim got an error when `string.find` call the nil. Its look like the `symbol.name` can be nil at sometime. Does its can count as a bug?

**Comment by stevearc** [comment]
Definitely a bug! Technically it's a bug in the language server, because [the LSP spec does not allow for name to be nil](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentSymbol). I added a commit that should work around the issue, but it would also be a good idea to report it upstream so it can get fixed in the server. Can I ask what server this is?

**Comment by Azrealy** [comment]
When I open my javascript file, it occurred this error. This error will gone after I remove the ember server. Which I think it because of ember server.

**Comment by stevearc** [comment]
Got it. Does my recent commit fix the issue for you?

**Comment by Azrealy** [comment]
Yes, its fixed!
