### ISSUE TITLE
UX: Display a better error message if the reason for no backends is `#lines > disable_max_lines`

### ISSUE THREAD

**Issue by b0o** [stevearc/aerial.nvim#186]
When attempting to open Aerial, if there is an appropriate backend but there are more than `disable_max_lines` lines in the current file, Aerial displays the notification "Aerial could find no supported backend". This confused me for a few minutes, until I ran `AerialInfo` and saw "File exceeds disable_max_lines size". It would be helpful if this information was included in the initial error message.

**Comment by stevearc** [comment]
That error message is left over from an earlier time. I think it makes more sense now to always open the aerial window, even if there are no symbols. This is more consistent with the behavior that happens if you open aerial and switch to an unsupported buffer. Plus, now we put some detailed diagnostic information in the window if there aren't any symbols, so it won't be as confusing!

**Comment by b0o** [comment]
> I think it makes more sense now to always open the aerial window, even if there are no symbols. 

I agree, this would be a nice improvement. Thanks for fixing this!
