### ISSUE TITLE
Error on switching from markdown to filetypes with LSP support

### ISSUE THREAD

**Issue by Bekaboo** [stevearc/aerial.nvim#193]
**Describe the bug**
When switching current file from markdown to other filetypes with LSP support, error occurs.

**System information**
- OS: Linux
- Neovim version: 0.8.1
- AerialInfo:
```
Aerial Info
-----------
Filetype: lua
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: all symbols
```
- Aerial config:
```lua
require('aerial').setup({
    keymaps = {
      ['?'] = false,
      ['<M-v>'] = 'actions.jump_vsplit',
      ['<C-v>'] = false,
      ['<M-s>'] = 'actions.jump_split',
      ['<C-s>'] = false,
    },
    disable_max_lines = 8192,
    filter_kind = false,
    icons = require('utils.static').icons,
    backends = { 'lsp', 'treesitter', 'markdown', 'man' },
    ignore = {
      filetypes = { 'aerial', 'help', 'alpha', 'undotree', 'TelescopePrompt' },
    },
    link_folds_to_tree = true,
    link_tree_to_folds = true,
    manage_folds = true,
    layout = {
      max_width = { 40, 0.25 },
      min_width = 20,
    },
    show_guides = true,
    float = { border = 'single' },
    treesitter = { update_delay = 10 },
    markdown = { update_delay = 10 },
  })
```

**To Reproduce**
1. Open a markdown file
2. `:AerialToggle`
3. Open another file with LSP support (for example, a lua file)

**Screenshots**

https://user-images.githubusercontent.com/76579810/207661516-6baecfbc-b025-4f5f-acb8-0e146ac68411.mp4

**Comment by stevearc** [comment]
That error is super weird. It seems to indicate that the nvim-treesitter utility `get_at_path` is nil. I initially thought that must have been a breaking API change in nvim-treesitter, but I checked and it's still there on the latest master. What does `:lua =require("nvim-treesitter.utils").get_at_path` display for you?

**Comment by Bekaboo** [comment]
> That error is super weird. It seems to indicate that the nvim-treesitter utility `get_at_path` is nil. I initially thought that must have been a breaking API change in nvim-treesitter, but I checked and it's still there on the latest master. What does `:lua =require("nvim-treesitter.utils").get_at_path` display for you?

The output is `<function 1>`, not nil. Can you reproduce this issue?

**Comment by Bekaboo** [comment]
I figured out the problem.
I lazy-load `nvim-treesitter` in my config (only load for specific filetypes, including lua, excluding markdown). When trying to switch from markdown to lua, aerial requires `nvim-treesitter` before it is loaded. Maybe adding `packadd nvim-treesitter` before requiring it will solve this? Or use a `pcall`?

**Comment by Bekaboo** [comment]
A temporary solution is removing `treesitter` from `backends` table.

**Comment by stevearc** [comment]
I'm already using a `pcall`. That means that it won't crash at import time, but _will_ produce errors later. IMO it doesn't make sense for any plugin to call `packadd` because that command uses the package name, not the lua module name. Technically using the packages system you could put all your packages under a package named "omni" in `site/pack/omni/opt/*`, and that would work fine. The names of packages are up to the discretion of the end user and not defined by the plugin.

Which then leaves the options:
* Lazy load nvim-treesitter before you load aerial
* Disable the treesitter backend
* Don't lazy load nvim-treesitter

Personally, after my experience trying out lazy loading, I think it's generally a bad idea. It can easily cause problems like this when plugins depend on or interact with each other.
