### ISSUE TITLE
Feature Request: Add support for treesitter's offset! directive

### ISSUE THREAD

**Issue by ColinKennedy** [stevearc/aerial.nvim#247]
Hello! Just to be clear upfront, this issue isn't for adding support for a new language but for an existing feature of treesitter. The context behind the request is for a new language but the parser is still WIP so I don't want to request it here yet.

Anyways ...

I'm writing a WIP treesitter parser for a language called [USD](https://www.pixar.com/usd). A typical file may look like this

```
def "foo"
{
    def "child_001"
    {
        # ... lots of stuff
    }

    def "child_002"
    {
        # ... lots of stuff
    }

    def "child_003"
    {
        # ... lots of stuff

        def "grand_child_001"
        {
            # ... lots of stuff
        }

        def "grand_child_002"
        {
            # ... lots of stuff
        }

        def "grand_child_003"
        {
            # ... lots of stuff
        }
    }
}
```

USD files can get very big with nested "def-s within def-s within def-s" with lots of data. Aerial.nvim has been a huge improvement for navigating those big files. That said, my parser matches the whole string name, `"foo"`, which Aerial picks up on, like this

```
"foo"
  "child_001"
  "child_002"
  "child_003"
    "grand_child_001"
    "grand_child_002"
    "grand_child_003"
```

I'd like to remove the prefix and suffix "s within aerial, without needing to modify the my original USD parser. I checked around neovim's `:help` and found `:help offset!`. The docs for that are as follows:

```
    `offset!`                                      *treesitter-directive-offset!*
        Takes the range of the captured node and applies an offset. This will
        generate a new range object for the captured node as
        `metadata[capture_id].range`.
```

It seemed like the perfect thing - I thought I should strip the start and end column so that the name becomes `foo`, rather than `"foo"`.

In a aerial.nvim fork ...

`queries/usd/aerial.scm`
```
(prim_definition
  (string) @name
  (#offset! @name 0 1 0 -1)
  (#set! "kind" "Class")
) @type
```

But I think the `#offset!` directive might not be known / supported by aerial because it doesn't seem to have any effect on the display tree that aerial creates. I'm getting around this for now, by adding the following to my own fork of aerial.nvim

`aerial.nvim/lua/aerial/backends/treesitter/extensions.lua`
```lua
M.usd = {
  postprocess = function(bufnr, item, match)
    item.name = item.name:gsub("^\"", "")
    item.name = item.name:gsub("\"$", "")
  end
}
```

Doing that renders the tree as I'd hoped

```
foo
  child_001
  child_002
  child_003
    grand_child_001
    grand_child_002
    grand_child_003
```

If there's a simpler way to query just the text within the string using treesitter query syntax I'd like to know (I'm a treesitter novice so I could've missed it in the docs). But if there's no alternative, adding the treesitter `offset!` directive seems like it'd be a good way to solve this sort of thing. What do you think?

**Comment by stevearc** [comment]
Querying the contents inside the string quotes is dependent on the parser. Some parsers assign a separate node to the inside of the quotes, some don't. If it's all a single node, then that's as far as you can go.

I've added support for offset ranges specifically for the `name` node. It would be a larger refactor to do this for the positioning nodes, or to do this for languages that already have special logic in the `extensions.lua` file. I mention this so that if you or someone else comes across examples where offset appears to not be working, this is why (and you can open a new issue for that situation).

Give the fix a try and see if it handles your use case.

**Comment by ColinKennedy** [comment]
I pulled the latest master commit but there's still ""s after attempting to modify the column range. I'm new to tree-sitter query syntax so I may not be doing it 100% right.

```scm
(prim_definition
  (string) @name
  (#offset! @name 0 1 0 -1)
  (#set! "kind" "Class")
) @type
```

That's the same block as my previous post. Since the offset is applying to `@name`, does that mean I should see a difference in the output?

My impression of the `#offset!` was that it can be used to modify the row/column range of a node without needing a separate inner node as you've said. That functionality doesn't come for free of course, which is why I appreciate you taking to time to try to add support for it. If my tree-sitter query can be improved to get this working, please let me know.

**Comment by stevearc** [comment]
I tested this by adding `(#offset! @name 0 1 0 -1)` after this line: https://github.com/stevearc/aerial.nvim/blob/3721075a6903859c4936bdc7e5a4c345f93d3aac/queries/lua/aerial.scm#L2

and running the tests for the lua parser with `./run_tests.sh tests/treesitter/lua_spec.lua`. The tests fail (as expected) because it trims out the function name.

That's about as far as I can help you without a repro. If you can get me an example or a test that I can run on my own computer then I can try to figure out what's going on.

**Comment by ColinKennedy** [comment]
In the process of reproing I think I solved whatever in my config that was preventing your commit from working. I'll report back if it breaks later but it looks like we're all set! I'll close this issue. Thank you for your timely replies and this plug-in. I'm really enjoying using it :)
