### ISSUE TITLE
New feature request: show frametitle of beamer in Latex

### ISSUE THREAD

**Issue by ChenZhongPu** [stevearc/aerial.nvim#270]
I am using `beamer` class in Latex to create slidesm, but `Aerial` only displays Latex environment names:

<img width="363" alt="image" src="https://github.com/stevearc/aerial.nvim/assets/2310958/2610b2bf-c65e-491d-a37f-52475c65d747">

Given a `beamer` class in Latex, it consists of many *frames*:

```tex
\begin{frame}
    \frametitle{Algorithm}
\end{frame}
```

What I expect is that the `frametitle` should be displayed, and all other nested environments should also be hidden.

**Comment by stevearc** [comment]
I don't know what you mean by "all other nested environments should also be hidden"
but you can add the `frametitle` to the symbols list if you're using the treesitter backend (which I don't know if you are, because you didn't include the output of `:AerialInfo`).

To add that symbol, just create a file under `<rtp>/after/queries/latex/aerial.scm` with the contents

```
; extends

(generic_command
  command: (command_name) @cmd (#eq? @cmd "\\frametitle")
  arg: (curly_group (text) @name)
  (#set! "kind" "Interface")
 ) @type
```

**Comment by ChenZhongPu** [comment]
> I don't know what you mean by "all other nested environments should also be hidden"

For a beamer class document, generally its outline should only contain `frame` environment, as what  LaTeX Workshop in VS Code does (shown in the figure below).

<img width="372" alt="image" src="https://github.com/stevearc/aerial.nvim/assets/2310958/9cc5011e-9b75-4f70-92ba-d4b8ad531d17">

As for displaying the title of a frame, it should be expect to handle two styles:

```tex
\begin{frame}
    \frametitle{Algorithm}
\end{frame}
```

```tex
\begin{frame}{Algorithm}
\end{frame}
```

**Comment by stevearc** [comment]
VS code is either doing this with a LSP (in which case you can just use the same LSP for aerial) or it has some special parsing logic to display that structure (because they don't have treesitter integrated). I see that you have a LSP attached, so you can try using that backend for aerial to see if it produces the output you want.

If you need to do this with treesitter, you'll have to override the default configuration. These rules are fine for the particular latex document you are working on, but are not suitable for latex as a whole. You can override the config by placing a file in `<rtp>/queries/latex/aerial.scm` with the contents

```
(generic_command
  command: (command_name) @cmd (#eq? @cmd "\\frametitle")
  arg: (curly_group (text) @name)
  (#set! "kind" "Interface")
 ) @type
```

You'll need a few more queries, but that should get you started

**Comment by ChenZhongPu** [comment]
[vimtex](https://github.com/lervag/vimtex/issues/2731#issuecomment-1604515312) solved this issue.
