### ISSUE TITLE
Doesn't work with multi-filetypes.

### ISSUE THREAD

**Issue by fullstopslash** [stevearc/aerial.nvim#33]
I have a really niche use case here. Both Vim and Neovim have a handy feature that allows a file to be recognized as multiple filetypes, then various scripts and autogroup actions can be ran for each of the filetypes that applies. As an example I'm using the [Vimwiki](https://github.com/vimwiki/vimwiki) plugin to edit markdown files, some types of markdown can also be considered a pandoc file as well.  In neovim if I open a markdown file and issue the command `:set filetype` it shows the current filetype as `vimwiki.markdown.pandoc` as expected. However, this plugin doesn't recognize this as a list of filetypes. Instead, as far as I can tell, it recognizes a single filetype `vimwiki.markdown.pandoc` and doesn't open.  For reference both [Tagbar](https://github.com/preservim/tagbar) and [Vista.vim](https://github.com/liuchengxu/vista.vim) work out of the box in recognizing the markdown structure in this case. At any rate, thanks again for this rad plugin! 

**System information**
- OS: mac
- Neovim version: v0.7.0-dev+758-g0c35fd5fc

Aerial Info
-----------
Filetype: vimwiki.markdown.pandoc
Configured backends:
  lsp (not supported)
treesitter (not supported)
markdown (not supported)
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct

**Comment by stevearc** [comment]
Quick note: this actually does work with the new [treesitter backend for markdown](https://github.com/stevearc/aerial.nvim/commit/d9436f2be9dda2ba2bd469243d69479876561275)! But you make a good point; aerial should absolutely support compound filetypes. I will get right on that!

**Comment by fullstopslash** [comment]
I've got a regression here. This is back to not working when  I list my filetype as:
`markdown = { "treesitter"},`
 now I'm using.
`["vimwiki.markdown.pandoc"] = { "treesitter" },`

**Comment by stevearc** [comment]
If you run `:AerialInfo`, which backend is attached? I suspect that you're on the treesitter backend now, because I re-ran some tests and the markdown backend works fine for me, but the treesitter one repros the issue.

The issue is with how treesitter parses compound filetypes.
https://github.com/nvim-treesitter/nvim-treesitter/blob/1f0771153542608a29cd06bacf2978adc40d1265/lua/nvim-treesitter/parsers.lua#L933
It takes just the part of the string before the first ".". So in your case, it will be looking up "vimwiki". They don't have a parser for that, so it fails. This means that all other TS features (highlighting, indenting) will not be working for you either.

I can think of 3 things that you could do:
1. Switch back to using the "markdown" backend (just put it first in the `backends` config option)
2. Change the filetype to `markdown.vimwiki.pandoc`
3. File an issue on nvim-treesitter to change how they handle compound filetypes
