### ISSUE TITLE
[ Bug ] Missing entry in aerial treesitter kind_map: impl_item

### ISSUE THREAD

**Issue by ten3roberts** [stevearc/aerial.nvim#48]
**Describe the bug**

**System information**
- OS: Linux
- Neovim version: 0.7.0-dev+876j
- AerialInfo: 
- Aerial Info                                                                                                                                                                                     
-----------                                                                                                                                                                                     
Filetype: rust                                                                                                                                                                                  
Configured backends:                                                                                                                                                                            
  lsp (supported) (attached)                                                                                                                                                                    
  treesitter (supported)                                                                                                                                                                        
  markdown (not supported)                                                                                                                                                                      
Show symbols: all symbols   
- Aerial config:
```lua
vim.g.aerial = {
  -- Enum: persist, close, auto, global
  --   persist - aerial window will stay open until closed
  --   close   - aerial window will close when original file is no longer visible
  --   auto    - aerial window will stay open as long as there is a visible
  --             buffer to attach to
  --   global  - same as 'persist', and will always show symbols for the current buffer
  close_behavior = "global",

  -- Set to false to remove the default keybindings for the aerial buffer
  default_bindings = true,

  -- Enum: prefer_right, prefer_left, right, left
  -- Determines the default direction to open the aerial window. The 'prefer'
  -- options will open the window in the other direction *if* there is a
  -- different buffer in the way of the preferred direction
  default_direction = "left",

  -- Set to true to only open aerial at the far right/left of the editor
  -- Default behavior opens aerial relative to current window
  placement_editor_edge = true,

  -- Fetch document symbols when LSP diagnostics change.
  -- If you set this to false, you will need to manually fetch symbols
  diagnostics_trigger_update = true,

  -- Enum: split_width, full_width, last, none
  -- Determines line highlighting mode when multiple buffers are visible
  highlight_mode = "split_width",

  -- When jumping to a symbol, highlight the line for this many ms
  -- Set to 0 or false to disable
  highlight_on_jump = 300,

  -- Fold code when folding the tree. Only works when manage_folds is enabled
  link_tree_to_folds = true,

  -- Fold the tree when folding code. Only works when manage_folds is enabled
  link_folds_to_tree = false,

  -- Use symbol tree for folding. Set to true or false to enable/disable
  -- 'auto' will manage folds if your previous foldmethod was 'manual'
  manage_folds = "auto",

  -- The maximum width of the aerial window
  max_width = 30,

  -- The minimum width of the aerial window.
  -- To disable dynamic resizing, set this to be equal to max_width
  min_width = 10,

  -- Set default symbol icons to use Nerd Font icons (see https://www.nerdfonts.com/)
  nerd_font = "auto",

  -- Whether to open aerial automatically when entering a buffer.
  -- Can also be specified per-filetype as a map (see below)
  open_automatic = true,

  -- If open_automatic is true, only open aerial if the source buffer is at
  -- least this long
  -- open_automatic_min_lines = 50,

  -- If open_automatic is true, only open aerial if there are at least this many symbols
  open_automatic_min_symbols = 1,

  -- Run this command after jumping to a symbol (false will disable)
  post_jump_cmd = "normal! zz",

  -- Set to false to not update the symbols when there are LSP errors
  update_when_errors = true,

  -- A list of all symbols to display. Set to false to display all symbols.
  filter_kind = false,
}

```

**To Reproduce**
1. Open Rust file
2. Wait for LSP rust-analyzer to attach
3. Sometimes the error will appear, however, not always.When renaming an item using LSP the error will always appear and prevent rename.

**Screenshots**
![Screenshot from 2022-01-16 12-06-21](https://user-images.githubusercontent.com/25723553/149657385-060f7742-d3e3-4b47-96fb-85eeafa7a251.png)

**Additional context**
The error message:

The cause for the error is that the `language_kind_map` for Rust is incomplete

File: `./lua/aerial/backends/treesitter/language_kind_map.lua`,

is missing `impl_item` in the kind map.

**Comment by stevearc** [comment]
There are...many things that I find confusing in this bug report.
1) `impl_item` is already in [language_kind_map.lua](https://github.com/stevearc/aerial.nvim/blob/ee3eab57a29dd4ccfc7d5c43ede114c621546750/lua/aerial/backends/treesitter/language_kind_map.lua#L87)
2) Furthermore, it was added in the same commit where the treesitter query was modified to query `impl_item` (e4c2e7e9c88d5e6d7d1f12f6d9e17f183bd0dd18), so I have no idea how *any* version could ever see that error
3) That message is printed with [nvim_err_writeln](https://github.com/stevearc/aerial.nvim/blob/ee3eab57a29dd4ccfc7d5c43ede114c621546750/lua/aerial/backends/treesitter/init.lua#L62-L64), not `error()`, so it shouldn't produce a stack
4) That stacktrace leads to a `vim.cmd` that's [setting up autocommands](https://github.com/stevearc/aerial.nvim/blob/ee3eab57a29dd4ccfc7d5c43ede114c621546750/lua/aerial/autocommands.lua#L90-L95) and has nothing to do with treesitter
5) LSP rename goes through entirely separate channels and should never even touch aerial code, so there should be no way for aerial to interfere with it.

That all means that I unfortunately don't even have a good guess what could be happening and can only give you general debugging advice.

* Try it on Neovim 0.6.1 (I did try to repro it on nightly, but couldn't)
* Try updating aerial
* Does LSP rename work if you disable/remove aerial? What about if you disable either the LSP or the treesitter backend for aerial? (`backends = {'treesitter'}` or `backends = {'lsp'}`)
* Does LSP rename work if you disable/remove rust-tools.nvim? (it's the only other plugin in your stack trace)
* Try logging more information at [the error location](https://github.com/stevearc/aerial.nvim/blob/ee3eab57a29dd4ccfc7d5c43ede114c621546750/lua/aerial/backends/treesitter/init.lua#L62-L64). What is the actual contents of `kind_map` at that location?

Hopefully one of these will help turn up some more information we can use to get to the root cause.

**Comment by ten3roberts** [comment]
The issue has been resolved.

Renaming works when disabled.

The reason was two conflicting installations of Aerial.

There was a leftover symbolic link in `rtpath` that was conflicting and was used instead of the github installation.

The leftover link came from previous forks when I was opening my last pull request.

It was entirely my fault as I thought I was using the most recent version after having paq show that Aerial was installed and updated.
