### ISSUE TITLE
Global Aerial window

### ISSUE THREAD

**Issue by ten3roberts** [stevearc/aerial.nvim#5]
When using many splits, especially with open_automatic enabled, it can easily become very cluttered and take up much space when each split has its own Aerial window.

Would it be possible to have one Aerial window on the very left or right that displays the current splits symbols, rather than one per split. I'm not intending this to be default behaviour, but maybe an option.

**Comment by stevearc** [comment]
I've added an option `close_behavior = 'global'` that will update the aerial window to display symbols for whatever buffer is currently focused. I'll also be adding another option soon to control the placement of the window and allow you to put it far left/right instead of attached to the side of the current buffer.

**Comment by stevearc** [comment]
Now also added `placement_editor_edge = true` to force the aerial window to be at the far left/right instead of attached to the source window.
