### ISSUE TITLE
Ruby rakefile

### ISSUE THREAD

**Issue by olimorris** [stevearc/aerial.nvim#63]
In Ruby, we often use `rakefiles` as a task runner. I myself use them to update my Mac's dependencies or set one up from fresh.

I've shown an example below from my config where I backup certain files. Would be great if `aerial` could show the namespace, desc and tasks. A namespace may have many descs and a desc may have many tasks.

**Language**: Ruby
**AerialInfo**:
```
Filetype: ruby
Configured backends:
  lsp (not supported) [LSP client not attached (did you call aerial.on_attach?)]
  treesitter (supported) (attached)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```

The minimal amount of code that demonstrates the missing symbol:
```ruby
namespace :backup do
  desc 'Backup PIP files'
  task :pip do
    section 'Backing up PIP files'

    run %( pip3 freeze \> #{PIP_FILE} )
  end

  desc 'Backup NPM files'
  task :npm do
    section 'Backing up NPM files'

    run %( npm -g upgrade )
    run %( npm list --global --parseable --depth=0 | sed '1d' | awk '\{gsub\(/\\/.*\\//,"",$1\); print\}' \> #{NPM_FILE} )
  end

  desc 'Backup Ruby Gems'
  task :gems do
    section 'Backing up Ruby Gems'

    run %( gem list --no-versions | sed '1d' | awk '\{gsub\(/\\/.*\\//,"",$1\); print\}' \> #{GEMS_FILE} )
  end
end

```

**Expected symbol**: Function

**Comment by stevearc** [comment]
I've added support for `namespace`, `file`, `task`, and `multitask`. I opted not to add `desc` for this first iteration because it's documentation, more like a docstring than a symbol. I don't think it belongs, but give this version a try and see if it works for you. We can make some tweaks if necessary.

**Comment by olimorris** [comment]
Great suggestion and works brilliantly.

Wondered if there's any reason why, when I enable aerial on the LSP, that it shows "No symbols"? Is it `solargraph` the Ruby LSP?

**Comment by stevearc** [comment]
You should still see symbols in normal Ruby files, but if you're speaking specifically about Rakefiles and Rspec: they simply don't have any symbols that would be recognized by *any* language server, not just solargraph. All of these `task :a_task` constructs are a function call, not a function definition. Ruby is just using its flexible language design to pass in a block to it and use it as a logical definition for the benefit of the developer, but at the language level it's indistinguishable from any other `foo('bar')` function call. We get around this with the treesitter backend because we can examine the AST and recognize these special cases, but with LSP you get what you get.

**Comment by olimorris** [comment]
Got it. I wondered if having `lsp` ahead of `treesitter` in the `backends` part of the setup would still enable results.

Anyway, thanks for all of your recent Ruby enhancements.

**Comment by stevearc** [comment]
Ah, nope the backends are one or the other. We take the first one that is supported by your editor configuration and leave the other.

**Comment by olimorris** [comment]
Nothing some conditionals in my `on_attach` function won't solve 😄

**Comment by stevearc** [comment]
You should also be able to set it on a per-filetype basis in the aerial config,
if you don't want to clutter your `on_attach`
```lua
require('aerial').setup({
  backends = {
    -- default to preferring LSP backend
    ["_"] = { "lsp", "treesitter", "markdown"},
    ruby = { "treesitter" },
  },
})
```

**Comment by olimorris** [comment]
The sheer beauty of `aerial` and `telescope`:

![Screen Shot 2022-03-02 at 22 09 46@2x](https://user-images.githubusercontent.com/9512444/156458087-172a4674-75a0-41eb-b78f-9aca607bacc6.png)
