### ISSUE TITLE
Error in the installation. No aerial command is available

### ISSUE THREAD

**Issue by anderson-silva-concordia** [stevearc/aerial.nvim#79]
After install aerial I get the error 

`ES108: Error  executing lua ...cker/start/aerial.nvim/lua/lualine/aerial.lua:90: attempt to index upvalue 'aerial' a boolean value)`

And no commands like :AerialToggle is available to me.

**System information**
- OS:Manjaro Linux x86_64
- Neovim version: NVIM v0.6.0-dev+119-g68f61b167
- AerialInfo: command not available
- Aerial config:
```lua
  use {'stevearc/aerial.nvim'}

And

require("aerial").on_attach(client, bufnr) 
```

**To Reproduce**
1. Just start neovim after install aerial and the error above appears.

**Comment by stevearc** [comment]
I don't know what, but something is going wrong with your environment. For one thing: that file does not exist. There's a file at lualine/ **components** /aerial.lua, and if you look at that file line 90 is just calling a method from the main aerial lib https://github.com/stevearc/aerial.nvim/blob/master/lua/lualine/components/aerial.lua#L90

That was required earlier with just `require('aerial')`, but the error claims that `aerial` is a boolean value instead of a table.

So, not sure how this happened, but somehow `package.loaded.aerial` has become a boolean. The most likely candidates I can think of are:
1. You've installed the package in multiple places and they're somehow conflicting
2. It looks like you're using packer. Packer does a lot of magic things under the hood, and one of those things could be having unintended side effects

**Comment by stevearc** [comment]
I don't use packer but I downloaded it again to try it, and it works fine for me. You could try the installation without packer to see if that works `git clone --depth=1 https://github.com/stevearc/aerial.nvim.git "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/aerial/start/aerial.nvim`

Beyond that, you'll just have to do some debugging with lua. Try to figure out what's even requiring the lualine component, because unless you've set up your lualine config to use the aerial component that directory shouldn't even be loaded.

**Comment by zbouslikhin** [comment]
> Thanks for your answer @stevearc
> 
> I checked and it look like the package is not being used anywhere else.
> 
> I removed the package and recompiled packer to clean everything up, reinstalled but the problem persists.
> 
> Do you have any suggestions? That what I could do next?

Same problem here.

**Comment by zbouslikhin** [comment]
> I don't use packer but I downloaded it again to try it, and it works fine for me. You could try the installation without packer to see if that works `git clone --depth=1 https://github.com/stevearc/aerial.nvim.git "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/aerial/start/aerial.nvim`
> 
> Beyond that, you'll just have to do some debugging with lua. Try to figure out what's even requiring the lualine component, because unless you've set up your lualine config to use the aerial component that directory shouldn't even be loaded.

Installing without packer also does not work - no commands available.

**Comment by stevearc** [comment]
@anderson-silva-concordia I did find and fix a bug related to the exact version of neovim that you're using. Strangely, I still couldn't repro the error trace you're reporting.

@zbouslikhin Are you also seeing the `attempt to index upvalue` error? And what version of neovim are you running?

Both of you: are you calling `require('aerial').setup({})` in your init.lua? It used to be that calling `setup()` wasn't required, but I changed that a few months ago for performance reasons and to better support lazy-loading. I realize that I didn't update the docs to that effect, so I've also made some changes to the README that should hopefully make it clear that calling `setup()` is required.

**Comment by zbouslikhin** [comment]
I was not calling `require('aerial').setup({})` in my init.lua. Doing so fixed the problem :) Thank you!

> @anderson-silva-concordia I did find and fix a bug related to the exact version of neovim that you're using. Strangely, I still couldn't repro the error trace you're reporting.
> 
> @zbouslikhin Are you also seeing the `attempt to index upvalue` error? And what version of neovim are you running?
> 
> Both of you: are you calling `require('aerial').setup({})` in your init.lua? It used to be that calling `setup()` wasn't required, but I changed that a few months ago for performance reasons and to better support lazy-loading. I realize that I didn't update the docs to that effect, so I've also made some changes to the README that should hopefully make it clear that calling `setup()` is required.
