### ISSUE TITLE
Go can not display hierarchically

### ISSUE THREAD

**Issue by crusj** [stevearc/aerial.nvim#81]
golang cannot display hierarchical relationships, such as struct and methods under structshould be displayed hierarchically
<img width="1705" alt="图片" src="https://user-images.githubusercontent.com/20185895/162600963-1926de80-7648-452b-b0ac-38e5797d446b.png">

**Comment by stevearc** [comment]
The trouble with Go is that there *isn't* a hierarchy to those symbols. Take this for example:
```go
type Foo struct {
  bar string
}

func Unrelated() int {
  return 5
}

func (f *Foo) Frobnicate() {
  fmt.Println("Fthrrrrpb")
}
```

How can you nest Frobnicate under Foo, while having the Unrelated function between them? Or worse, what if Frobnicate is defined in a completely different file? You could potentially special-case it when methods are defined *right* below the struct, but I think the lack of consistency would be confusing.

A different idea, but somewhat related: what about if method names show up namespaced under their struct? So instead of `getname` you would see `FSB.getname`?

**Comment by crusj** [comment]
<img width="1691" alt="图片" src="https://user-images.githubusercontent.com/20185895/162907860-e2281747-a6f3-4924-8d6c-992982ee9373.png">
Still not working, what am I missing？

**Comment by stevearc** [comment]
So you're suggesting we re-arrange the symbols in the list like Goland? I see why that works for Goland, but it would cause problems in aerial. Take for example, the code folding feature. Aerial can link the symbols window with your code folds. What happens if you collapse the class? The code folds can't possibly be updated to reflect the aerial state. Or a more common case: navigating to next/prev symbol. We would have to choose if `:AerialNext` goes to the next symbol *in the list*, or the next *in the code*. No matter which we choose, 50% of the time it's going to do something unexpected for the user.

Reordering or restructuring symbols is almost guaranteed to interact negatively with other features, because instead of displaying the real structure of the code you're displaying something else. Other features rely on the structure being accurate. This was why I suggested that the names of the methods could be updated to reflect the parent class. Names are much safer to play with.

**Comment by crusj** [comment]
> So you're suggesting we re-arrange the symbols in the list like Goland? I see why that works for Goland, but it would cause problems in aerial. Take for example, the code folding feature. Aerial can link the symbols window with your code folds. What happens if you collapse the class? The code folds can't possibly be updated to reflect the aerial state. Or a more common case: navigating to next/prev symbol. We would have to choose if `:AerialNext` goes to the next symbol _in the list_, or the next _in the code_. No matter which we choose, 50% of the time it's going to do something unexpected for the user.
> 
> Reordering or restructuring symbols is almost guaranteed to interact negatively with other features, because instead of displaying the real structure of the code you're displaying something else. Other features rely on the structure being accurate. This was why I suggested that the names of the methods could be updated to reflect the parent class. Names are much safer to play with.

What I mean is to express that the hierarchical relationship between classes and methods of plugins does not take effect in go, but it seems to take effect in Lua. Folding is not required, but there should be indentation between the structure and the methods it has.

**Comment by stevearc** [comment]
What you want is a view of the Go structs, paired with their methods across the project. That sounds like a useful tool, and could make a great plugin, but that is not what Aerial does.

Aerial uses language-agnostic interfaces (LSP and Treesitter) to display and navigate notable language constructs (classes, functions, etc) in a single file.

Trying to make Aerial do the things you are asking would require a lot of special-case code just for Go, and it would break a lot of Aerial features not related specifically to viewing. For that reason, those features are not a viable addition to Aerial.

For language-specific customization that we *can* do, see [extensions.lua](https://github.com/stevearc/aerial.nvim/blob/master/lua/aerial/backends/treesitter/extensions.lua). It ranges from tweaking the display of Rust trait implementations to supporting the display of Jest tests as symbols.

**Comment by crusj** [comment]
> What you want is a view of the Go structs, paired with their methods across the project. That sounds like a useful tool, and could make a great plugin, but that is not what Aerial does.
> 
> Aerial uses language-agnostic interfaces (LSP and Treesitter) to display and navigate notable language constructs (classes, functions, etc) in a single file.
> 
> Trying to make Aerial do the things you are asking would require a lot of special-case code just for Go, and it would break a lot of Aerial features not related specifically to viewing. For that reason, those features are not a viable addition to Aerial.
> 
> For language-specific customization that we _can_ do, see [extensions.lua](https://github.com/stevearc/aerial.nvim/blob/master/lua/aerial/backends/treesitter/extensions.lua). It ranges from tweaking the display of Rust trait implementations to supporting the display of Jest tests as symbols.

Well.

**Comment by crusj** [comment]
I wrote a plugin like I described.
[https://github.com/crusj/structrue-go.nvim](https://github.com/crusj/structrue-go.nvim)

**Comment by ppwwyyxx** [comment]
> Reordering or restructuring symbols is almost guaranteed to interact negatively with other features, because instead of displaying the real structure of the code you're displaying something else. Other features rely on the structure being accurate. This was why I suggested that the names of the methods could be updated to reflect the parent class. Names are much safer to play with.

Hi @stevearc , I agree with your argument that restructuring the symbols might conflict with other features. However, the restructuring can be very useful sometimes. Here is an example screenshot on [this file](https://github.com/KDE/kscreen/blob/master/kded/daemon.cpp):

## aerial.nvim:

![2022-06-22_23-41](https://user-images.githubusercontent.com/1381301/175232581-0c5e4b84-41be-4059-aa7c-653164a05750.png)

## [preservim/tagbar](https://github.com/preservim/tagbar)

![2022-06-22_23-42](https://user-images.githubusercontent.com/1381301/175232633-b5a0fdf3-9bb1-4f6a-b2c7-c1e7a9c9191b.png)


As you can see, restructuring the symbols allow tagbar plugin to show less redundant information than aerial.nvim. As a result we are able to fit more information within the given width.

The other features are not as important to me as the basic experience of viewing a clean set of tags. I think it would be great for aerial.nvim to support such restructuring as an option, although it may have to disable some other features.

**Comment by stevearc** [comment]
The trouble is that this would require a lot of custom code specifically for go, all throughout the codebase of aerial. At the moment there is [a single location](https://github.com/stevearc/aerial.nvim/blob/master/lua/aerial/backends/treesitter/extensions.lua) that handles language-specific features and that's pretty maintainable, but something of this scale would require handling in a bunch of different places across the project.

On top of that, some of the built-in features (navigation, folding) will break. So if this change requires a whole lot of custom code that fights with the existing structure, *and* it doesn't get to make use of several of aerial's features, why then would we add it to aerial? It seems like it would make more sense as a separate plugin. 

Fundamentally, aerial is using language-independent tools (LSP, treesitter) to provide a set of common functionality across languages. Because of that, it is limited to making certain assumptions about the layout of code that are common but not universal. That means that, much like LSP itself, it is sacrificing having the *best* functionality for a *specific* language in order to have *good* functionality for *most* languages.

I 100% agree that what you're asking for looks like a good and useful tool, but unfortunately I just don't think that it makes sense to try to add it to this project.
