### ISSUE TITLE
(How to) Lazy load only if relevant backends are available (i.e. treesitter parser is installed or lsp server is configured and attached)

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/aerial.nvim#92]
Currently, it is unclear if `aerial.nvim` can be conditionally loaded only for those filetypes/buftypes for which either:
- a treesitter parser has been installed, or
- an LSP server has been installed, configured and attached

It shall be great if `aerial.nvim` can provide a detection mechanism either built into the plugin itself or with a user-hook to lazy load the plugin upon either of the above conditions being met?  Otherwise, it is slightly wasteful to load up `aerial` for a filetype with no  suitable backend.

**Comment by krishnakumarg1984** [comment]
I am interested in lazy-loading based on detecting the existence of a relevant treesitter parser.

In your plugin, can you perhaps consider running a pre-load script to see if the TS parser for the current filetype is installed, and then load the rest of `aerial` only if the filetype's TS parser has been loaded?

**Comment by stevearc** [comment]
Sure, it's easy to lazy-load with LSP because you can put the `vim.cmd[[packadd aerial.nvim]]` inside your on_attach function, which you probably already have. There's no such callback for TS attach, so you'd need to create an autocmd on BufEnter or FileType that checks if there's a parser and then run packadd.

To be clear, this is logic that aerial is already running once it's loaded, so this is only going to save you the time it takes for the initial `require('aerial')`. That clocks in at under 4ms on my system, while instrumented.

![aerial profile](https://user-images.githubusercontent.com/506791/166613304-a0b93bca-ef32-4a93-b8f1-953d200b1078.png)

If you want to shave off those 4ms by lazy-loading, go for it! But I'm happy enough with the startup time that I'm not inclined to increase the code complexity for it.

**Comment by krishnakumarg1984** [comment]
Cool. Thank you for the detailed reply. I am satisfied with the current default loading times and have decided against such micro-optimisations. Thanks again!

**Comment by krishnakumarg1984** [comment]
Actually, having this feature (i.e. lazy loading only if Treesitter parser is available or LSP server is attached to buffer) is really helpful when we have the following custom `open_automatic` function:

```
    open_automatic = function(bufnr)
      return not vim.opt.diff:get()                   -- if not in 'diff' mode
        and vim.api.nvim_buf_line_count(bufnr) > 26   -- Enforce a minimum line count
        and require("aerial").num_symbols(bufnr) > 3  -- Enforce a minimum symbol count
        and not require("aerial").was_closed()        -- A useful way to keep aerial closed when closed manually
    end,
```

In this case, when opening a file, only if treesitter or LSP backends are available for the current buffer does `aerial` needs to be loaded.  Can you please help me with the config lines to be added to my `init.lua` for the treesitter and LSP backends using packer.

**Comment by stevearc** [comment]
I don't think packer has anything built-in that allows you to do this, but I am far from an expert there. If you want to do it manually, you'll need to create some sort of wrapper function
```lua
function _G.lazy_load_aerial()
  if not package.loaded.aerial then
    vim.cmd([[packadd aerial.nvim]])
    require('aerial').setup({})
  end
end
```

Then call it in your LSP on_attach function:
```lua
if client.server_capabilities.documentSymbolProvider then
  lazy_load_aerial()
end
```

And create an autocmd for treesitter:
```lua
vim.api.nvim_create_autocmd('FileType', {
  pattern = '*',
  callback = function()
    local parsers = require("nvim-treesitter.parsers")
    local query = require("nvim-treesitter.query")
    local lang = parsers.get_buf_lang(0)
    if parsers.has_parser(lang) and query.has_query_files(lang, "aerial") then
      lazy_load_aerial()
    end
  end
})
```

That may need some tweaking, but that's the general idea
