### ISSUE TITLE
Automatically trigger `:AerialClose` on entering vim's diff-mode

### ISSUE THREAD

**Issue by krishnakumarg1984** [stevearc/aerial.nvim#97]
When we enter `diff` mode (detected by `&diff` in vimscript and with `vim.opt.diff:get()` in the lua api), I think that a reasonable action would be to close any opened `aerial` windows. 

When viewing a diff, the user is interested in the changes between the contents of two windows, and most people would like to have only those two windows in the current view.

**Comment by stevearc** [comment]
While that may be desirable in most cases, I don't think it makes sense to add this logic into aerial. Aerial gives you plenty of handles for display options so that you have complete control over when and how it is displayed. It doesn't make sense for the aerial plugin itself to try to predict how you want it to behave, because that forces opinions upon you. If you want to run some custom logic when entering diff mode, that should live in your own vim config. You'll have to do that anyway if you want to close the loclist, quickfix, etc.
